### ISSUE TITLE
CocoaPods could not find compatible versions for pod "rms-mobile-xdk-cocoapods"

### ISSUE THREAD

**Issue by ElaineKong** [RazerMS/Mobile-XDK-RazerMS_IOS#1]
![image](https://user-images.githubusercontent.com/13358323/129660121-a1c47df8-21ac-499a-b48a-b1a9ccf6011f.png)

**Comment by wasddsaw** [comment]
Hi @ElaineKong, for cocoapods latest version   3.30.0, please refer this link https://cocoapods.org/pods/rms-mobile-xdk-cocoapods

**Comment by ElaineKong** [comment]
> Hi @ElaineKong, for cocoapods latest version 3.30.0, please refer this link https://cocoapods.org/pods/rms-mobile-xdk-cocoapods

Isn't the latest version is 3.31.0 for Handle Cash-TH barcode? Why is it unavailable in cocoapods?

**Comment by hisyamadzha** [comment]
> > Hi @ElaineKong, for cocoapods latest version 3.30.0, please refer this link https://cocoapods.org/pods/rms-mobile-xdk-cocoapods
> 
> Isn't the latest version is 3.31.0 for Handle Cash-TH barcode? Why is it unavailable in cocoapods?

Kindly check for the update from this link https://cocoapods.org/pods/rms-mobile-xdk-cocoapods

**Comment by ElaineKong** [comment]
> > > Hi @ElaineKong, for cocoapods latest version 3.30.0, please refer this link https://cocoapods.org/pods/rms-mobile-xdk-cocoapods
> > 
> > 
> > Isn't the latest version is 3.31.0 for Handle Cash-TH barcode? Why is it unavailable in cocoapods?
> 
> Kindly check for the update from this link https://cocoapods.org/pods/rms-mobile-xdk-cocoapods

Same issue persists

**Comment by hisyamadzha** [comment]
<img width="565" alt="Screenshot 2021-08-18 at 9 14 06 AM" src="https://user-images.githubusercontent.com/38680137/129820854-6cac0105-4ad5-4085-a680-ffc5655d9a3d.png">

@ElaineKong We already test it and no issue. What can we suggest is, try to create fresh project and follow below step.

1. Run pod init
2. Paste pod 'rms-mobile-xdk-cocoapods', '~> 3.31' inside pod file
3. Run pod install
